# Credits

This is heavily influenced or copied from https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used. If you have a cuda enabled machine, read the README.md in the root of this repo on how to use nvidia-docker.


It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [1]:
import torch

Construct a 5x3 matrix, uninitialized

In [25]:
x = torch.Tensor(5, 3)
print(x)

tensor([[0.0001, 0.0000, 0.0001],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0001]])


Construct a randomly initialized matrix

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4698, 0.9412, 0.3096],
        [0.3216, 0.4802, 0.2024],
        [0.6027, 0.3260, 0.4116],
        [0.2395, 0.3605, 0.4109],
        [0.9470, 0.4962, 0.3623]])


Get its size

In [4]:
print(x.size())

torch.Size([5, 3])


**NOTE** `torch.Size` is in fact a tuple, so it supports the same operations

In [5]:
x[1:3] = 2
print(x)

tensor([[0.4698, 0.9412, 0.3096],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.2395, 0.3605, 0.4109],
        [0.9470, 0.4962, 0.3623]])


# Assignment

1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [23]:
x = torch.Tensor(2,17)
print(x.size())

torch.Size([2, 17])


In [14]:
xf = torch.FloatTensor(3,1)
print(xf.size())
print(xf.dtype)

torch.Size([3, 1])
torch.float32


In [17]:
xl = torch.LongTensor(5,2,1)
print(xl.size())
print(xl.dtype)
xl[:] = 7
print(xl)

torch.Size([5, 2, 1])
torch.int64
tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]]])


In [21]:
xb = torch.ByteTensor(5,)
xb[:] = 0   # Set all to 0
xb[1:4] = 1 # Set middle to 1
print(xb.size())
print(xb.dtype)
print(xb)


torch.Size([5])
torch.uint8
tensor([0, 1, 1, 1, 0], dtype=torch.uint8)


## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [26]:
y = torch.rand(5, 3)
print(x + y)

tensor([[0.2963, 0.5879, 0.2128],
        [0.7149, 0.7339, 0.7864],
        [0.7058, 0.7951, 0.8697],
        [0.7735, 0.2330, 0.5441],
        [0.3074, 0.2277, 0.8327]])


### 2.2 Addition: syntax 2

In [27]:
print(torch.add(x, y))

tensor([[0.2963, 0.5879, 0.2128],
        [0.7149, 0.7339, 0.7864],
        [0.7058, 0.7951, 0.8697],
        [0.7735, 0.2330, 0.5441],
        [0.3074, 0.2277, 0.8327]])


### 2.3 Addition: giving an output tensor

In [28]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.2963, 0.5879, 0.2128],
        [0.7149, 0.7339, 0.7864],
        [0.7058, 0.7951, 0.8697],
        [0.7735, 0.2330, 0.5441],
        [0.3074, 0.2277, 0.8327]])


### 2.4 Addition: in-place

adds `x`to `y`

In [29]:
y.add_(x)
print(y)

tensor([[0.2963, 0.5879, 0.2128],
        [0.7149, 0.7339, 0.7864],
        [0.7058, 0.7951, 0.8697],
        [0.7735, 0.2330, 0.5441],
        [0.3074, 0.2277, 0.8327]])


**NOTE** Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [31]:
print(x)
print(x[:, 1])

tensor([[0.0001, 0.0000, 0.0001],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0001]])
tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000])


**Read later** 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiply of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [37]:
torch.mul(x,y)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0001]])

## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [38]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [39]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.

In [40]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [41]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a numpy array
3. now convert it back to a torch tensor

In [44]:
a = torch.ones(5,2)
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [46]:
a_numpy = a.numpy()
a_numpy

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)

In [47]:
a_torch = torch.from_numpy(a_numpy)
a_torch

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [ ]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # this is meant as a tensor to be run on the GPU.
    # the .cuda() does this to any parameter it is applied to
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machie.")